# temp-directory: "./.nyc_output"
check-coverage: true
per-file: true
lines: 90
statements: 90
functions: 90
branches: 90
all: true
include: [
  "src/**/*.js"
]
instrument: true
reporter: [
  "lcov",
  "text-summary",
  "html"
]
report-dir: "./coverage_combined"
exclude: [
  "**/node_modules/**",
  '**/migrations/**',
  '**/docs/**',
]
