version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: cs_int_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=central_ledger
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=central_ledger_integration
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    # command: --skip-grant-tables

  kafka:
    image: johnnypark/kafka-zookeeper:2.3.0
    container_name: cs_int_kafka
    # # Disable logging as it is far too verbose for debugging locally
    # logging:
    #   driver: none
    volumes:
      - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ZOO_LOG4J_PROP=WARN
    healthcheck:
      test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","localhost:9092"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
