version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: cs_int_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./test/int/docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=central_ledger
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=central_ledger_integration
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  kafka:
    image: spotify/kafkaproxy
    container_name: cs_int_kafka
    # Disable logging as it is far too verbose for debugging locally
    # logging:
    #   driver: none
    # volumes:
    #   - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ZOO_LOG4J_PROP=WARN
      - ADVERTISED_HOST=${KAFKA_ADVERTISED_HOST:-localhost}
      - ADVERTISED_PORT=9092
      - CONSUMER_THREADS=1
      - TOPICS=my-topic,some-other-topic
      - ZK_CONNECT=kafka7zookeeper:2181/root/path
      - GROUP_ID=mymirror
    healthcheck:
      test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","localhost:9092"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
  central-settlement:
    build:
      dockerfile: test-integration.Dockerfile
      context: .
    container_name: cs_central-settlement
    links:
      - mysql
      - kafka
    ports:
      - "3007:3007"
    volumes:
      - ./test/int/docker/central-settlement/default.json:/opt/central-settlement/config/default.json
      - ./test:/opt/central-settlement/test
      - ./src:/opt/central-settlement/src
      - ./migrations:/opt/central-settlement/migrations
      - ./seeds:/opt/central-settlement/seeds
    command:
      - tail
      - -f
      - /dev/null
    environment:
      - DB_HOST=mysql
